In [7]:
import pandas as pd

df = pd.read_csv("C:/Users/pc/OneDrive/Desktop/heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [9]:
from scipy.stats import zscore

# Select numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
numeric_cols

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease'],
      dtype='object')

In [11]:
# Calculate Z-score for numeric columns
z_scores = df[numeric_cols].apply(zscore)
z_scores

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
0,-1.433140,0.410909,0.825070,-0.551341,1.382928,-0.832432,-1.113115
1,-0.478484,1.491752,-0.171961,-0.551341,0.754157,0.105664,0.898380
2,-1.751359,-0.129513,0.770188,-0.551341,-1.525138,-0.832432,-1.113115
3,-0.584556,0.302825,0.139040,-0.551341,-1.132156,0.574711,0.898380
4,0.051881,0.951331,-0.034755,-0.551341,-0.581981,-0.832432,-1.113115
...,...,...,...,...,...,...,...
913,-0.902775,-1.210356,0.596393,-0.551341,-0.188999,0.293283,0.898380
914,1.536902,0.627078,-0.053049,1.813758,0.164684,2.357094,0.898380
915,0.370100,-0.129513,-0.620168,-0.551341,-0.857069,0.293283,0.898380
916,0.370100,-0.129513,0.340275,-0.551341,1.461525,-0.832432,0.898380
917,-1.645286,0.302825,-0.217696,-0.551341,1.422226,-0.832432,-1.113115

In [27]:
# Keep only rows where all Z-scores are within [-3, 3]
df = df[(z_scores < 3).all(axis=1) & (z_scores > -3).all(axis=1)]
df

C:\Users\pc\AppData\Local\Temp\ipykernel_24320\4079361220.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[(z_scores < 3).all(axis=1) & (z_scores > -3).all(axis=1)]

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,False,True,False,False,False,True,False,False,False,True
1,49,0,160,180,0,156,0,1.0,1,False,False,True,False,False,True,False,False,True,False
2,37,1,130,283,0,98,0,0.0,0,False,True,False,False,False,False,True,False,False,True
3,48,0,138,214,0,108,1,1.5,1,True,False,False,False,False,True,False,False,True,False
4,54,1,150,195,0,122,0,0.0,0,False,False,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1.2,1,False,False,False,True,False,True,False,False,True,False
914,68,1,144,193,1,141,0,3.4,1,True,False,False,False,False,True,False,False,True,False
915,57,1,130,131,0,115,1,1.2,1,True,False,False,False,False,True,False,False,True,False
916,57,0,130,236,0,174,0,0.0,1,False,True,False,False,True,False,False,False,True,False
917,38,1,138,175,0,173,0,0.0,0,False,False,True,False,False,True,False,False,False,True

In [29]:
# Check how many rows are left
print("Number of rows after removing outliers:", len(df))

Number of rows after removing outliers: 899

In [31]:
##✅ Step 3: Convert Text Columns to Numbers

In [33]:
##✅ Step 3A: Find All Text Columns
# Show columns with object (text) data type
text_columns = df.select_dtypes(include='object').columns
print("Text columns in the dataset:")
print(text_columns)

Text columns in the dataset:
Index([], dtype='object')

In [54]:
##✅ Step 3B: Handle Categorical Columns
#1. Label Encode Binary Columns (2 unique values only)
from sklearn.preprocessing import LabelEncoder

# Create label encoder
le = LabelEncoder()

# Encode binary columns (e.g. 'Sex', 'ExerciseAngina')
df['Sex'] = le.fit_transform(df['Sex'])  # M/F → 1/0
df['ExerciseAngina'] = le.fit_transform(df['ExerciseAngina'])  # Y/N → 1/0

In [55]:
df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,False,True,False,False,False,True,False,False,False,True
1,49,0,160,180,0,156,0,1.0,1,False,False,True,False,False,True,False,False,True,False
2,37,1,130,283,0,98,0,0.0,0,False,True,False,False,False,False,True,False,False,True
3,48,0,138,214,0,108,1,1.5,1,True,False,False,False,False,True,False,False,True,False
4,54,1,150,195,0,122,0,0.0,0,False,False,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1.2,1,False,False,False,True,False,True,False,False,True,False
914,68,1,144,193,1,141,0,3.4,1,True,False,False,False,False,True,False,False,True,False
915,57,1,130,131,0,115,1,1.2,1,True,False,False,False,False,True,False,False,True,False
916,57,0,130,236,0,174,0,0.0,1,False,True,False,False,True,False,False,False,True,False
917,38,1,138,175,0,173,0,0.0,0,False,False,True,False,False,True,False,False,False,True

In [58]:
# Find columns with text (object) datatype
categorical_cols = df.select_dtypes(include='object').columns

print("Categorical columns are:")
print(categorical_cols)

Categorical columns are:
Index([], dtype='object')

In [59]:
# Show unique values in each categorical column
for col in categorical_cols:
    print(f"\n{col} - unique values:")
    print(df[col].unique())

In [60]:
# Separate columns for each encoding method
binary_cols = ['Sex', 'ExerciseAngina']
one_hot_cols = ['ChestPainType', 'RestingECG', 'ST_Slope']

In [61]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Apply Label Encoding
for col in binary_cols:
    df[col] = le.fit_transform(df[col])

# Check results
df[binary_cols].head()

   Sex  ExerciseAngina
0    1               0
1    0               0
2    1               0
3    0               1
4    1               0

In [64]:
print("Current columns in df:")
print(df.columns.tolist())

Current columns in df:
['Age', 'Sex', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'HeartDisease', 'ChestPainType_ASY', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_LVH', 'RestingECG_Normal', 'RestingECG_ST', 'ST_Slope_Down', 'ST_Slope_Flat', 'ST_Slope_Up']

In [65]:
one_hot_cols = ['chest_pain', 'resting_ecg', 'st_slope']  # use exact names from your DataFrame

In [67]:
# Get one-hot encoded columns (those with underscores and known prefixes)
encoded_cols = [col for col in df.columns if col.startswith('ChestPainType_') or 
                                              col.startswith('RestingECG_') or 
                                              col.startswith('ST_Slope_')]

print("One-hot encoded columns:")
print(encoded_cols)

One-hot encoded columns:
['ChestPainType_ASY', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_LVH', 'RestingECG_Normal', 'RestingECG_ST', 'ST_Slope_Down', 'ST_Slope_Flat', 'ST_Slope_Up']

In [68]:
df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,False,True,False,False,False,True,False,False,False,True
1,49,0,160,180,0,156,0,1.0,1,False,False,True,False,False,True,False,False,True,False
2,37,1,130,283,0,98,0,0.0,0,False,True,False,False,False,False,True,False,False,True
3,48,0,138,214,0,108,1,1.5,1,True,False,False,False,False,True,False,False,True,False
4,54,1,150,195,0,122,0,0.0,0,False,False,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1.2,1,False,False,False,True,False,True,False,False,True,False
914,68,1,144,193,1,141,0,3.4,1,True,False,False,False,False,True,False,False,True,False
915,57,1,130,131,0,115,1,1.2,1,True,False,False,False,False,True,False,False,True,False
916,57,0,130,236,0,174,0,0.0,1,False,True,False,False,True,False,False,False,True,False
917,38,1,138,175,0,173,0,0.0,0,False,False,True,False,False,True,False,False,False,True

In [69]:
df = df.astype(int)
df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,0,1,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,1,1,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,0,0,0,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1,1,0,0,0,1,0,1,0,0,1,0
914,68,1,144,193,1,141,0,3,1,1,0,0,0,0,1,0,0,1,0
915,57,1,130,131,0,115,1,1,1,1,0,0,0,0,1,0,0,1,0
916,57,0,130,236,0,174,0,0,1,0,1,0,0,1,0,0,0,1,0
917,38,1,138,175,0,173,0,0,0,0,0,1,0,0,1,0,0,0,1

In [72]:
df_encoded=df
df_encoded

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,0,1,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,1,1,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,0,0,0,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1,1,0,0,0,1,0,1,0,0,1,0
914,68,1,144,193,1,141,0,3,1,1,0,0,0,0,1,0,0,1,0
915,57,1,130,131,0,115,1,1,1,1,0,0,0,0,1,0,0,1,0
916,57,0,130,236,0,174,0,0,1,0,1,0,0,1,0,0,0,1,0
917,38,1,138,175,0,173,0,0,0,0,0,1,0,0,1,0,0,0,1

In [75]:
from sklearn.preprocessing import StandardScaler

# Separate features (X) and target (y)
X = df_encoded.drop('HeartDisease', axis=1)
y = df_encoded['HeartDisease']

# Apply StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [77]:
df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,0,1,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,1,1,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,0,0,0,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1,1,0,0,0,1,0,1,0,0,1,0
914,68,1,144,193,1,141,0,3,1,1,0,0,0,0,1,0,0,1,0
915,57,1,130,131,0,115,1,1,1,1,0,0,0,0,1,0,0,1,0
916,57,0,130,236,0,174,0,0,1,0,1,0,0,1,0,0,0,1,0
917,38,1,138,175,0,173,0,0,0,0,0,1,0,0,1,0,0,0,1

In [78]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score, classification_report

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Standalone SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

print("Standalone SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

Standalone SVM Accuracy: 0.8804347826086957
              precision    recall  f1-score   support

           0       0.85      0.87      0.86        77
           1       0.90      0.89      0.90       107

    accuracy                           0.88       184
   macro avg       0.88      0.88      0.88       184
weighted avg       0.88      0.88      0.88       184

In [80]:

# SVM with Bagging
bagging_svm = BaggingClassifier(estimator=SVC(), n_estimators=10, random_state=42)
bagging_svm.fit(X_train, y_train)
y_pred_bag_svm = bagging_svm.predict(X_test)

print("Bagged SVM Accuracy:", accuracy_score(y_test, y_pred_bag_svm))
print(classification_report(y_test, y_pred_bag_svm))

Bagged SVM Accuracy: 0.8913043478260869
              precision    recall  f1-score   support

           0       0.85      0.90      0.87        77
           1       0.92      0.89      0.90       107

    accuracy                           0.89       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.89      0.89      0.89       184

In [81]:
from sklearn.tree import DecisionTreeClassifier

# Standalone Decision Tree
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)
y_pred_tree = tree_model.predict(X_test)

print("Standalone Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))
print(classification_report(y_test, y_pred_tree))

Standalone Decision Tree Accuracy: 0.8097826086956522
              precision    recall  f1-score   support

           0       0.72      0.88      0.80        77
           1       0.90      0.76      0.82       107

    accuracy                           0.81       184
   macro avg       0.81      0.82      0.81       184
weighted avg       0.83      0.81      0.81       184

In [83]:
# Decision Tree with Bagging
bagging_tree = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=10, random_state=42)
bagging_tree.fit(X_train, y_train)
y_pred_bag_tree = bagging_tree.predict(X_test)

print("Bagged Decision Tree Accuracy:", accuracy_score(y_test, y_pred_bag_tree))
print(classification_report(y_test, y_pred_bag_tree))

Bagged Decision Tree Accuracy: 0.8586956521739131
              precision    recall  f1-score   support

           0       0.78      0.92      0.85        77
           1       0.94      0.81      0.87       107

    accuracy                           0.86       184
   macro avg       0.86      0.87      0.86       184
weighted avg       0.87      0.86      0.86       184

In [84]:
### 💡 Analysis: When to Use Bagging?

- **SVMs** are already stable models — Bagging may not improve much.
- **Decision Trees** are unstable — Bagging can significantly help reduce variance and improve performance.

📌 **Bagging is best when:**
- Base models are high-variance (e.g., decision trees).
- You want to reduce overfitting.
- You have enough data to allow training multiple models.

SyntaxError: invalid character '—' (U+2014) (1384291578.py, line 3)